# Generated by Django 4.2.11 on 2024-03-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.FloatField()),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('period', models.FloatField()),
                ('date', models.DateField()),
                ('result', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.FloatField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=2)),
                ('type', models.CharField(max_length=4)),
                ('days', models.FloatField()),
                ('date', models.DateField()),
                ('interest', models.DecimalField(decimal_places=2, max_digits=20)),
                ('result', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
