# Generated by Django 4.2.11 on 2024-03-25 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('first_day', models.DecimalField(decimal_places=0, max_digits=2)),
                ('first_month', models.DecimalField(decimal_places=0, max_digits=2)),
                ('first_year', models.DecimalField(decimal_places=0, max_digits=5)),
                ('end_day', models.DecimalField(decimal_places=0, max_digits=2)),
                ('end_month', models.DecimalField(decimal_places=0, max_digits=2)),
                ('end_year', models.DecimalField(decimal_places=0, max_digits=5)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=20)),
                ('result', models.DecimalField(decimal_places=2, max_digits=20)),
                ('type', models.CharField(choices=[('p.a.', 'p.a.'), ('p.s.', 'p.s.'), ('p.q.', 'p.q.'), ('p.m.', 'p.m.')], max_length=4)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompoundInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('period', models.PositiveIntegerField()),
                ('fvif', models.DecimalField(decimal_places=2, max_digits=30)),
                ('result', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
