# Generated by Django 4.2.11 on 2024-03-17 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoundinterest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simpleinterest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='simpleinterest',
            name='type',
            field=models.CharField(choices=[('p.a.', 360), ('p.s.', 180), ('p.q.', 90), ('p.m.', 30)], max_length=4),
        ),
    ]
