# Generated by Django 4.2.11 on 2024-03-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0002_compoundinterest_user_simpleinterest_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleinterest',
            name='type',
            field=models.CharField(choices=[('p.a.', 'p.a.'), ('p.s.', 'p.s.'), ('p.q.', 'p.q.'), ('p.m.', 'p.m.')], max_length=4),
        ),
    ]
